# Generated by Django 2.1.7 on 2019-03-14 03:06

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myalmanack', '0002_auto_20190312_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2019, 3, 13))]),
        ),
    ]
