# Generated by Django 2.1.7 on 2019-04-25 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRequest',
            fields=[
                ('invite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.Invite')),
            ],
            options={
                'db_table': 'Group_Request',
                'managed': False,
            },
            bases=('database.invite',),
        ),
    ]
